<h2 style='color:red;' align='center'>KFold Cross Validation Python Tutorial</h2>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)
print(len(X_train),len(X_test))

1257 540


**Logistic Regression**

In [21]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9592592592592593

**SVM**

In [22]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.43703703703703706

**Random Forest**

In [23]:
rf = RandomForestClassifier(n_estimators=43)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9814814814814815

<h2 style='color:purple'>KFold cross validation</h2>

**Basic example**

In [31]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [36]:
from sklearn.model_selection import StratifiedKFold
kf = StratifiedKFold(n_splits=3)
kf

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [37]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9],[0,0,0,0,0,1,1,1,1]):
    print(train_index, test_index)

[2 3 4 6 7 8] [0 1 5]
[0 1 4 5 7 8] [2 3 6]
[0 1 2 3 5 6] [4 7 8]


**Use KFold for our digits example**

In [41]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [46]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=5)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=69), X_train, X_test, y_train, y_test))

In [47]:
scores_logistic

[0.9222222222222223,
 0.8833333333333333,
 0.9526462395543176,
 0.958217270194986,
 0.8941504178272981]

In [48]:
scores_svm

[0.4111111111111111,
 0.45,
 0.45403899721448465,
 0.44846796657381616,
 0.479108635097493]

In [49]:
scores_rf

[0.9305555555555556,
 0.9194444444444444,
 0.958217270194986,
 0.9721448467966574,
 0.9275766016713092]

<h2 style='color:purple'>cross_val_score function</h2>

In [50]:
from sklearn.model_selection import cross_val_score

**Logistic regression model performance using cross_val_score**

In [51]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=5)

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

**svm model performance using cross_val_score**

In [54]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

**random forest performance using cross_val_score**

In [53]:
cross_val_score(RandomForestClassifier(n_estimators=69),digits.data, digits.target,cv=5)

array([0.94166667, 0.90833333, 0.95821727, 0.96100279, 0.93871866])

cross_val_score uses stratifield kfold by default

<h2 style='color:purple'>Parameter tunning using k fold cross validation</h2>

In [64]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1*100)

87.92396027312228

In [63]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2*100)

94.60148975791432

In [62]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=69),digits.data, digits.target, cv=10)
np.average(scores3*100)

95.10180012414648

In [61]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=52),digits.data, digits.target, cv=10)
np.average(scores4*100)

94.65673494723774

Here we used cross_val_score to
fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result. 

<h2 style='color:purple'>Exercise</h2>

Use iris flower dataset from sklearn library and use cross_val_score against following
models to measure the performance of each. In the end figure out the model with best performance,
1. Logistic Regression
2. SVM
3. Decision Tree
4. Random Forest