In [5]:
import numpy as np

In [6]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

<h3 style='color:blue'>Implement Mean Absolute Error</h3>

In [9]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    # return mae

In [10]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


**Implement same thing using numpy in much easier way**

In [11]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [12]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.5)

In [13]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [14]:
mae_np(y_predicted, y_true)

np.float64(0.5)

<h3 style='color:blue'>Implement Log Loss or Binary Cross Entropy</h3>

In [30]:
np.log([2.74988779])

array([1.01156011])

In [31]:
epsilon = 1e-15

In [33]:
epsilon

1e-15

In [32]:
np.log([1e-15])

array([-34.53877639])

In [34]:
y_predicted

array([1, 1, 0, 0, 1])

In [35]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [36]:
1-epsilon

0.999999999999999

In [37]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [38]:
y_predicted_new = np.array(y_predicted_new)

In [39]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [40]:
np.log(y_predicted)

/tmp/ipykernel_13490/815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [41]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(17.2696280766844)

In [42]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [43]:
log_loss(y_true, y_predicted)

np.float64(17.2696280766844)

<h3 style='color:purple'>Exercise</h3>

Implement mean squared error (or MSE) in two ways,

1) Without using numpy (i.e. using plain python)

2) With the use of numpy

In [46]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [47]:
def mse(y_predicted,y_true):
    total_error=0
    for yp,yt in zip(y_predicted,y_true):
        total_error += (yp-yt)**2
    print(f" Total error is {total_error}")
    mse=total_error/len(y_predicted)
    print(f" MSE is {mse}")

In [48]:
mse(y_predicted,y_true)

 Total error is 1.83
 MSE is 0.366


In [51]:
print(np.mean(np.square(y_predicted-y_true)))

0.366


[Solution](https://github.com/codebasics/py/tree/master/DeepLearningML/5_loss/loss_function_exercise_solution.ipynb)